# User tmux configuration
source-file /etc/tmux.conf
set-option -g default-shell /usr/bin/zsh

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse on
set-option -g set-titles on
set-option -g set-titles-string '#T'

#set-option -g automatic-rename on
#set-option -g automatic-rename-format '#{pane_current_command}'

